### ISSUE TITLE
Init NX Workspace

### ISSUE THREAD

**Issue by louiiuol** [louiiuol/la-methode-claire#4]
# Context 📝

_Create a monorepo containing all applications related to `La méthode claire`'s project._

## MonoRepo Architecture

![Image](https://user-images.githubusercontent.com/14725008/210175892-87428cee-d10b-43cb-9863-1724462536a8.png)

# TODO 💪

- [x] Generate empty mono repo w/ Nx
- [x] Add Angular applications: `lmc-admin-ui` - `lmc-app-ui'
- [x] Add Nextjs application: `lmc-public-ui`
- [x] Add NestJS API: `lmc-api`

# Sources 🔗

- [Angular Architecture Introduction](https://www.youtube.com/watch?v=j38ufd8Q86w&t=962s)
- [NX Packages](https://nx.dev/packages)
